-  name: java
   yum:
     name:
      - openjdk-11-jdk
      - openjdk-8-jdk
     state: latest
     update_cache: yes

- name: export java_home
  shell: export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 
  args:
    chdir: /home/ubuntu/spring-petclinic

- name: install mvnw
  shell:   ./mvnw package     
  args:
    chdir: /home/ubuntu/spring-petclinic
    creates: /home/centos/spring-petclinic/target
    
- name: java jar
  shell: 'nohup java -jar /home/ubuntu/spring-petclinic/target/*.jar  & ' 
    
