-  name: java
   yum:
     name:
      - openjdk-8-jdk
     state: latest
     update_cache: yes

- name: export java_home
  shell: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 
  args:
    chdir: /home/ubuntu/spring-petclinic

- name: install mvnw
  shell: ./mvnw package     
  args:
    creates: /home/ubuntu/spring-petclinic/target/*.jar 
    chdir: /home/ubuntu/spring-petclinic

- name: java jar
  shell: 'nohup java -jar /home/ubuntu/spring-petclinic/target/*.jar  & ' 
    
