- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

-  name: java
   yum:
     name:
      - openjdk-11-jdk
      - openjdk-8-jdk
     state: latest
     update_cache: yes

- name: etc environment
  shell: export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 chdir=/home/ubuntu/spring-petclinic

- name: etc profile
  shell: export  PATH=$PATH:$JAVA_HOME/bin chdir=/home/ubuntu/spring-petclinic

- name: bash_profile
  shell: |
    echo JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64  > /home/ubuntu/spring-petclinic/.profile

- name: source
  shell: source /home/ubuntu/spring-petclinic/.profile
  become: yes
  args:
    creates: /bin/bash

- name: install mvnw
  shell:   ./mvnw package     chdir=/home/ubuntu/spring-petclinic

- name: java jar
  shell: 'nohup java -jar /home/ubuntu/spring-petclinic/target/*.jar  & ' 
    
