- name: Install git
  package:
    name:
      - git
    state: latest


- name: Clone a spring repo 
  git:
    repo: "{{ spring_repo }}" 
    dest: /home/ubuntu/spring-petclinic
    version: "{{ spring_branch }}"
    
