- name: Install git
  yum:
    name:
      - git
    state: latest


- name: Clone a spring repo
  git:
    repo: "{{ spring_repo }}" 
    dest: /home/centos/spring-petclinic
    version: "{{ spring_branch }}"
    
